// descriptions gave on Emojipedia.org
var titles = ["🔍", "😀", "🦊", "🅰️", "🍎", "🏳️‍🌈", "🏊", "🖱️", "👗", "🖐️", "🛎️"];
var emojis = [];

/*search*/
emojis[0] = {};
/*smileys*/
emojis[1] = {
    "😀": [":)", "Grinning Face", "Happy Face", "Smiley Face"],
    "😃": [":D", "Grinning Face with Big Eyes", "Happy Face", "Smiley Face", "Smiling Face with Open Mouth"],
    "😄": ["Grinning Face with Smiling Eyes", "Happy Face", "Smiley Face", "Grinning Face With Squinting Eyes", "Smiling Face with Open Mouth and Smiling Eyes"],
    "😁": ["Beaming Face with Smiling Eyes", "Grinning Face with Smiling Eyes"],
    "😆": ["xD", "><", "Grinning Squinting Face", "Big Grin", "Closed-Eyes Smile", "Laughing", "Grinning Face With Tightly Closed Eyes", "Smiling Face with Open Mouth and Tightly-Closed Eyes"],
    "😅": ["Grinning Face with Sweat", "Exercise", "Happy Sweat", "Grinning Face With Squinting Eyes and Sweat Drop", "Smiling Face with Open Mouth and Cold Sweat"],
    "🤣": ["ROFL", "Rolling on the Floor Laughing"],
    "😂": ["Face with Tears of Joy", "Laughing", "Laughing Crying", "Laughing Tears", "LOL"],
    "🙂": [":)", "Slightly Smiling Face", "Slightly Happy", "This Is Fine"],
    "🙃": ["Upside-Down Face", "Sarcasm", "Silly", "Upside Down Face"],
    "😉": [";)", "Winking Face", "Wink", "Wink Face", "Winky Face"],
    "😊": ["^^", "Smiling Face with Smiling Eyes", "Happy Face", "Smile", "Smiley Face"],
    "😇": ["Smiling Face with Halo", "Angel", "Halo"],
    "🥰": ["Smiling Face with Hearts", "In Love Face", "Smiling Face with Smiling Eyes and Three Hearts"],
    "😍": ["Smiling Face with Heart-Eyes", "Heart Eyes", "Heart Face", "Smiling Face with Heart-Shaped Eyes"],
    "🤩": ["Star-Struck", "Excited", "Star Eyes", "Starry Eyed", "Wow Face", "Face With Starry Eyes", "Grinning Face with Star Eyes"],
    "😘": [":*", ":-*", "Face Blowing a Kiss", "Blow A Kiss", "Blowing Kiss", "Kissing", "Face Throwing a Kiss"],
    "😗": [":*", ":-*", "Kissing Face", "Duck Face", "Kissy Face", "Whistling"],
    "☺️": ["Smiling Face", "Happy Face", "Smiley Face", "Smiling", "White Smiling Face"],
    "😚": ["Kissing Face with Closed Eyes", "Kiss Face", "Kissy Face"],
    "😙": ["Kissing Face with Smiling Eyes", "Kiss Face", "Kissy", "Whistle", "Whistling"],
    "😋": ["Face Savoring Food", "Goofy", "Hungry", "Smiling Face Licking Lips", "Face Savouring Delicious Food"],
    "😛": [":P", "Face with Tongue", "Cheeky", "Tongue Face", "Tongue-Out", "Face with Stuck-Out Tongue"],
    "😜": [";P", "Winking Face with Tongue", "Crazy", "Crazy Face", "Winking Face With Stuck-Out Tongue", "Face with Stuck-Out Tongue and Winking Eye"],
    "🤪": ["Zany Face", "Crazy Eyes", "Excited", "Wild", "Goofy Face", "Grinning Face with One Large and One Small Eye"],
    "😝": ["xP", "Squinting Face with Tongue", "Tongue Out", "Face With Stuck Out Tongue and Tightly-Closed Eyes", "Face with Stuck-Out Tongue and Tightly-Closed Eyes"],
    "🤑": ["$", "Money-Mouth Face", "Dollar Sign Eyes", "Money Face", "Rich"],
    "🤗": ["Hugging Face", "Hug", "Hugging", "Hugs", "Happy Face With Hugging Hands"],
    "🤭": ["Oops", "Face with Hand Over Mouth", "Smiling Face with Smiling Eyes and Hand Covering Mouth"],
    "🤫": ["Shh", "Shush", "Shushing Face", "Hush", "Quiet", "Silence", "Silent", "Face with Finger Covering Closed Lips"],
    "🤔": ["What", "?", "Hmm", "Thinking Face", "Chin Thumb", "Thinker", "Throwing Shade"],
    "🤐": ["Zip", "Zipper-Mouth Face", "Lips Sealed", "Sealed Lips", "Zip It", "Face With a Zipper Mouth"],
    "🤨": ["Face with Raised Eyebrow", "Colbert", "The Rock", "Face With Raised Eyebrow", "Face with One Eyebrow Raised"],
    "😐": [":|", "Neutral Face", "Face With Straight Mouth", "Straight Faced"],
    "😑": ["-_-", "Expressionless Face", "Face With Straight Mouth", "Straight Face"],
    "😶": ["Face Without Mouth", "Blank Face", "Mouthless", "Silence", "Silent"],
    "😏": ["Smirking Face", "Flirting", "Sexual Face", "Smug Face", "Suggestive Smile"],
    "😒": ["Unamused Face", "Dissatisfied", "Meh", "Side-Eye", "Unimpressed"],
    "🙄": ["Face with Rolling Eyes", "Eye Roll"],
    "😬": ["Grimacing Face", "Awkward", "Eek", "Foot In Mounth", "Nervous", "Snapchat Mutual #1 Best Friend"],
    "🤥": ["Lying Face", "Liar", "Long Nose", "Pinocchio"],
    "😌": ["Relieved Face", "Content", "Pleased"],
    "😔": ["Sorry", "Pensive Face", "Pensive", "Sad", "Sadface", "Sorrowful", "Sad Pensive Face"],
    "😪": ["Sleepy Face", "Side-Tear", "Snot Bubble", ],
    "🤤": ["Saliva", "Drooling Face", "Drool"],
    "😴": ["Zzz", "Sleeping Face", "Sleep Face", "Snoring", "Zzz Face"],
    "😷": ["Face with Medical Mask", "Coronavirus", "COVID-19", "Mask Face", "Surgical Mask"],
    "🤒": ["Face with Thermometer", "Ill", "Sick"],
    "🤕": ["Face with Head-Bandage", "Bandaged Head", "Clumsy", "Injured"],
    "🤢": ["Nauseated Face", "Disgust", "Green Face", "Vomit"],
    "🤮": ["Face Vomiting", "Spew", "Bleah", "Bleurgh", "Yuk", "Yuck", "Ew", "Spew", "Throwing Up", "Vomit", "Face with Open Mouth Vomiting"],
    "🤧": ["Sneezing Face", "Gesundheit"],
    "🥵": ["Hot Face", "Overheated Face"],
    "🥶": ["Cold Face", "Cool", "Chill", "Freezing Face"],
    "🥴": ["Woozy Face", "Drunk Face", "Face with Uneven Eyes and Wavy Mouth"],
    "😵": ["Dizzy Face", "Cross Eyes Face", "Spiral Eyes Face"],
    "🤯": ["Exploding Head", "Mind Blown", "Shocked Face with Exploding Head"],
    "🤠": ["Cowboy Hat Face", "Cowboy", "Cowboy Face", "Face with Cowboy Hat"],
    "🥳": ["Partying Face", "Party Face", "Face with Party Horn and Party Hat"],
    "😎": ["Smiling Face with Sunglasses", "Cool", "Mutual Best Friends (Snapchat)", "Sunglasses"],
    "🤓": ["Nerd Face", "Nerdy"],
    "🧐": ["Face with Monocle"],
    "😕": [":/", ":S", "Confused Face", "Nonplussed", "Puzzled"],
    "😟": [":(", "Worried Face", "Sad", "Sadface"],
    "🙁": [":(", "Slightly Frowning Face", "Slightly Sad"],
    "☹️": [":(", "Frowning Face", "Megafrown", "White Frowning Face"],
    "😮": [":O", "Wow", "Oh my!", "Face with Open Mouth", "Open Mouth", "Surprised Face With Open Mouth"],
    "😯": [":O", "Hushed Face", "Surprise", "Surprised Face"],
    "😲": [":O", "Wow", "Astonished Face", "Drunk Face", "Gasping Face", "Shocked Face"],
    "😳": [":$", "Flushed Face", "Blushing Face", "Embarrassed", "Shame", "Face With Wide Open Eyes"],
    "🥺": [":(", "Pleading Face", "Begging", "Glossy Eyes", "Simp", "Face with Pleading Eyes"],
    "😦": ["D:", "Frowning Face with Open Mouth", "Yawning"],
    "😨": ["D:", "Fearful Face", "Scared", "Surprised"],
    "😰": ["Anxious Face with Sweat", "Blue Face", "Concerned Face", "Nervous Face", "Face with Open Mouth and Cold Sweat"],
    "😥": [":'(", "Sad but Relieved Face", "Eyebrow Sweat", "Disappointed but Relieved Face"],
    "😢": [":'(", "Crying Face", "Crying", "Tear"],
    "😭": ["Loudly Crying Face", "Bawling", "Crying", "Sad Tears", "Sobbing"],
    "😱": ["Face Screaming in Fear", "Home Alone", "Scream", "Screaming Face"],
    "😖": ["Confounded Face", "Quivering Mouth", "Scrunched Face"],
    "😣": ["Persevering Face", "Helpless Face", "Scrunched Eyes"],
    "😞": [":(", "Disappointed Face", "Sad", "Sadface"],
    "😓": ["Downcast Face with Sweat", "Hard Work", "Sad Sweat Face", "Face with Cold Sweat"],
    "😩": [],
    "😫": [],
    "😤": [],
    "😡": [],
    "😠": [],
    "🤬": [],
    "😈": [],
    "👿": [],
    "🤡": [],
    "👽": [],
    "👾": [],
    "🤖": [],
    "👹": [],
    "👻": [],
    "👶": [],
    "🧒": [],
    "👧": [],
    "🧑": [],
    "👱": [],
    "👨": [],
    "🧔": [],
    "👨‍🦰": [],
    "👨‍🦱": [],
    "👨‍🦳": [],
    "👨‍🦲": [],
    "👩": [],
    "👩‍🦰": [],
    "👩‍🦱": [],
    "👩‍🦳": [],
    "👩‍🦲": [],
    "👱‍♀️": [],
    "👱‍♂️": [],
    "🧓": [],
    "👴": [],
    "👵": [],
    "👼": [],
    "🎅": [],
    "🤶": [],
    "🤴": [],
    "👸": [],
    "👳": [],
    "👳‍♂️": [],
    "👳‍♀️": [],
    "👲": [],
    "🧕": [],
    "🤵": [],
    "👰": [],
    "🤰": [],
    "🤱": []
};
/*animals*/
emojis[2] = {
    "😺": [],
    "😸": [],
    "😹": [],
    "😻": [],
    "😼": [],
    "😽": [],
    "🙀": [],
    "😿": [],
    "😾": [],
    "🙈": [],
    "🙉": [],
    "🙊": [],
    "🐵": [],
    "🐒": [],
    "🦍": [],
    "🐶": [],
    "🐕": [],
    "🐩": [],
    "🐺": [],
    "🦊": [],
    "🦝": [],
    "🐱": [],
    "🐈": [],
    "🦁": [],
    "🐯": [],
    "🐅": [],
    "🐆": [],
    "🐴": [],
    "🐎": [],
    "🦄": [],
    "🦓": [],
    "🦌": [],
    "🐮": [],
    "🐂": [],
    "🐃": [],
    "🐄": [],
    "🐷": [],
    "🐖": [],
    "🐗": [],
    "🐽": [],
    "🐏": [],
    "🐑": [],
    "🐐": [],
    "🐪": [],
    "🐫": [],
    "🦙": [],
    "🦒": [],
    "🐘": [],
    "🦏": [],
    "🦛": [],
    "🐭": [],
    "🐁": [],
    "🐀": [],
    "🐹": [],
    "🐰": [],
    "🐇": [],
    "🐿️": [],
    "🦔": [],
    "🦇": [],
    "🐻": [],
    "🐨": [],
    "🐼": [],
    "🦘": [],
    "🦡": [],
    "🦃": [],
    "🐔": [],
    "🐓": [],
    "🐣": [],
    "🐤": [],
    "🐥": [],
    "🐦": [],
    "🐧": [],
    "🕊️": [],
    "🦅": [],
    "🦆": [],
    "🦢": [],
    "🦉": [],
    "🦚": [],
    "🦜": [],
    "🐸": [],
    "🐊": [],
    "🐢": [],
    "🦎": [],
    "🐍": [],
    "🐲": [],
    "🐉": [],
    "🦕": [],
    "🦖": [],
    "🐳": [],
    "🐋": [],
    "🐬": [],
    "🐟": [],
    "🐠": [],
    "🐡": [],
    "🦈": [],
    "🐙": [],
    "🐚": [],
    "🐌": [],
    "🦋": [],
    "🐛": [],
    "🐜": [],
    "🐝": [],
    "🐞": [],
    "🦗": [],
    "🕷️": [],
    "🦂": [],
    "🦟": [],
    "🦀": [],
    "🦞": [],
    "🦐": [],
    "🦑": []
};
/*symbols*/
emojis[3] = {
    "💘": [],
    "💝": [],
    "💖": [],
    "💗": [],
    "💓": [],
    "💞": [],
    "💕": [],
    "💟": [],
    "❣️": [],
    "💔": [],
    "❤️": [],
    "🧡": [],
    "💛": [],
    "💚": [],
    "💙": [],
    "💜": [],
    "🖤": [],
    "🤍": [],
    "🤎": [],
    "💯": [],
    "💬": [],
    "💤": [],
    "♠️": [],
    "♥️": [],
    "♦️": [],
    "♣️": [],
    "🏧": [],
    "🎵": [],
    "🎶": [],
    "🔔": [],
    "🔕": [],
    "🔈": [],
    "🔉": [],
    "🔊": [],
    "🔇": [],
    "⛔": [],
    "🚫": [],
    "🚳": [],
    "🚭": [],
    "🚯": [],
    "🚱": [],
    "🚷": [],
    "🔞": [],
    "☢️": [],
    "☣️": [],
    "⬆️": [],
    "↗️": [],
    "➡️": [],
    "↘️": [],
    "⬇️": [],
    "↙️": [],
    "⬅️": [],
    "↖️": [],
    "↕️": [],
    "↔️": [],
    "↩️": [],
    "↪️": [],
    "⤴️": [],
    "⤵️": [],
    "🔃": [],
    "🔄": [],
    "🔙": [],
    "🔚": [],
    "🔛": [],
    "🔜": [],
    "🔝": [],
    "🛐": [],
    "⚛️": [],
    "🕉️": [],
    "✡️": [],
    "☸️": [],
    "☯️": [],
    "✝️": [],
    "☦️": [],
    "☪️": [],
    "☮️": [],
    "🕎": [],
    "🔯": [],
    "♈": [],
    "♉": [],
    "♊": [],
    "♋": [],
    "♌": [],
    "♍": [],
    "♎": [],
    "♏": [],
    "♐": [],
    "♑": [],
    "♒": [],
    "♓": [],
    "⛎": [],
    "🔀": [],
    "🔁": [],
    "🔂": [],
    "▶️": [],
    "◀️": [],
    "🔼": [],
    "🔽": [],
    "⏩": [],
    "⏪": [],
    "⏫": [],
    "⏬": [],
    "⏹️": [],
    "⏏️": [],
    "🎦": [],
    "📶": [],
    "✖️": [],
    "➕": [],
    "➖": [],
    "➗": [],
    "♾️": [],
    "‼️": [],
    "⁉️": [],
    "❓": [],
    "❔": [],
    "❕": [],
    "❗": [],
    "⭕": [],
    "☑️": [],
    "✔️": [],
    "❌": [],
    "✅": [],
    "❎": [],
    "#️⃣": [],
    "0️⃣": [],
    "1️⃣": [],
    "2️⃣": [],
    "3️⃣": [],
    "4️⃣": [],
    "5️⃣": [],
    "6️⃣": [],
    "7️⃣": [],
    "8️⃣": [],
    "9️⃣": [],
    "🔟": [],
    "🔠": [],
    "🔡": [],
    "🔢": [],
    "🔤": [],
    "🅰️": [],
    "🆎": [],
    "🅱️": [],
    "🆑": [],
    "🆒": [],
    "🆓": [],
    "ℹ️": [],
    "🆔": [],
    "🆕": [],
    "🅾️": [],
    "🆗": [],
    "🅿️": [],
    "🆘": [],
    "🆙": [],
    "🆚": [],
    "🔴": [],
    "🔵": [],
    "⚫": [],
    "⚪": [],
    "⬛": [],
    "⬜": [],
    "🔶": [],
    "🔷": [],
    "🔸": [],
    "🔹": [],
    "🔺": [],
    "🔻": [],
    "🔳": [],
    "🔲": [],
    "©️": [],
    "®️": [],
    "™️": []
};
/*food and drinks*/
emojis[4] = {
    "🍇": [],
    "🍈": [],
    "🍉": [],
    "🍊": [],
    "🍋": [],
    "🍌": [],
    "🍍": [],
    "🥭": [],
    "🍎": [],
    "🍏": [],
    "🍐": [],
    "🍑": [],
    "🍒": [],
    "🍓": [],
    "🥝": [],
    "🍅": [],
    "🥥": [],
    "🥑": [],
    "🍆": [],
    "🥔": [],
    "🥕": [],
    "🌽": [],
    "🌶️": [],
    "🥒": [],
    "🥬": [],
    "🥦": [],
    "🍄": [],
    "🥜": [],
    "🌰": [],
    "🍞": [],
    "🥐": [],
    "🥖": [],
    "🥨": [],
    "🥯": [],
    "🥞": [],
    "🧀": [],
    "🍖": [],
    "🍗": [],
    "🥩": [],
    "🥓": [],
    "🍔": [],
    "🍟": [],
    "🍕": [],
    "🌭": [],
    "🥪": [],
    "🌮": [],
    "🌯": [],
    "🥙": [],
    "🍳": [],
    "🥘": [],
    "🍲": [],
    "🥣": [],
    "🥗": [],
    "🍿": [],
    "🧂": [],
    "🥫": [],
    "🍱": [],
    "🍘": [],
    "🍙": [],
    "🍚": [],
    "🍛": [],
    "🍜": [],
    "🍝": [],
    "🍠": [],
    "🍢": [],
    "🍣": [],
    "🍤": [],
    "🍥": [],
    "🥮": [],
    "🍡": [],
    "🥟": [],
    "🥠": [],
    "🥡": [],
    "🍦": [],
    "🍧": [],
    "🍨": [],
    "🍩": [],
    "🍪": [],
    "🎂": [],
    "🍰": [],
    "🧁": [],
    "🥧": [],
    "🍫": [],
    "🍬": [],
    "🍭": [],
    "🍮": [],
    "🍯": [],
    "🍼": [],
    "🥛": [],
    "☕": [],
    "🍵": [],
    "🍶": [],
    "🍾": [],
    "🍷": [],
    "🍸": [],
    "🍹": [],
    "🍺": [],
    "🍻": [],
    "🥂": [],
    "🥃": [],
    "🥤": [],
    "🥢": [],
    "🍽️": [],
    "🍴": [],
    "🥄": []
};
/*flags*/
emojis[5] = {
    "🏁": [],
    "🚩": [],
    "🎌": [],
    "🏴": [],
    "🏳️": [],
    "🏳️‍🌈": [],
    "🏳️‍⚧️": [],
    "🏴‍☠️": [],
    "🇺🇳": [],
    "🇪🇺": [],
    "🇧🇸": [],
    "🇨🇦": [],
    "🇨🇭": [],
    "🇨🇳": [],
    "🇩🇪": [],
    "🇩🇰": [],
    "🇪🇪": [],
    "🇪🇬": [],
    "🇪🇸": [],
    "🇫🇮": [],
    "🇫🇷": [],
    "🇬🇧": [],
    "🇬🇱": [],
    "🇬🇷": [],
    "🇭🇺": [],
    "🇮🇪": [],
    "🇮🇱": [],
    "🇮🇩": [],
    "🇮🇳": [],
    "🇮🇶": [],
    "🇮🇷": [],
    "🇮🇸": [],
    "🇮🇹": [],
    "🇯🇵": [],
    "🇯🇲": [],
    "🇰🇪": [],
    "🇰🇷": [],
    "🇰🇵": [],
    "🇱🇺": [],
    "🇲🇹": [],
    "🇲🇽": [],
    "🇳🇴": [],
    "🇳🇱": [],
    "🇳🇿": [],
    "🇵🇱": [],
    "🇵🇹": [],
    "🇷🇺": [],
    "🇸🇪": [],
    "🇸🇮": [],
    "🇹🇳": [],
    "🇺🇦": [],
    "🇺🇸": [],
    "🇻🇪": [],
    "🇻🇬": [],
    "🇻🇮": [],
    "🇿🇦": [],
    "🇿🇼": [],
    "🇦🇪": [],
    "🇦🇷": [],
    "🇦🇹": [],
    "🇦🇺": [],
    "🇧🇷": []
};
/*sports*/
emojis[6] = {
    "🧗": [],
    "🏇": [],
    "⛷️": [],
    "🏂": [],
    "🏌️": [],
    "🏄": [],
    "🚣": [],
    "🏊": [],
    "⛹️": [],
    "🏋️": [],
    "🚴": [],
    "🚵": [],
    "🤸": [],
    "🤼": [],
    "🤽": [],
    "🤾": [],
    "🤹": [],
    "🧘": [],
    "🏆": [],
    "🏅": [],
    "🥇": [],
    "🥈": [],
    "🥉": [],
    "⚽": [],
    "⚾": [],
    "🥎": [],
    "🏀": [],
    "🏐": [],
    "🏈": [],
    "🏉": [],
    "🎾": [],
    "🥏": [],
    "🎳": [],
    "🏏": [],
    "🏑": [],
    "🏒": [],
    "🥍": [],
    "🏓": [],
    "🏸": [],
    "🥊": [],
    "🥋": [],
    "⛳": [],
    "⛸️": [],
    "🎣": [],
    "🎽": [],
    "🎿": [],
    "🛷": [],
    "🥌": [],
    "🎯": [],
    "🎱": [],
    "🎮": [],
    "♟️": [],
    "🏹": []
};
/*technologies (smartphones, laptops, ect.) and office*/
emojis[7] = {
    "⌚": [],
    "⏰": [],
    "⏱️": [],
    "⏲️": [],
    "🕰️": [],
    "🕹️": [],
    "🎙️": [],
    "🎚️": [],
    "🎛️": [],
    "📻": [],
    "📱": [],
    "📲": [],
    "☎️": [],
    "📞": [],
    "📟": [],
    "📠": [],
    "🔋": [],
    "🔌": [],
    "💻": [],
    "🖥️": [],
    "🖨️": [],
    "⌨️": [],
    "🖱️": [],
    "🖲️": [],
    "💽": [],
    "💾": [],
    "💿": [],
    "📀": [],
    "🎥": [],
    "🎞️": [],
    "📽️": [],
    "📺": [],
    "📷": [],
    "📸": [],
    "📹": [],
    "📼": [],
    "💳": [],
    "📧": [],
    "📨": [],
    "📩": [],
    "📤": [],
    "📥": [],
    "📮": [],
    "📁": [],
    "📂": [],
    "🗂️": [],
    "📅": [],
    "📈": [],
    "📉": [],
    "📊": [],
    "📌": [],
    "📋": [],
    "📍": [],
    "📎": [],
    "📏": [],
    "📐": [],
    "✂️": [],
    "✏️": [],
    "✒️": [],
    "🖋️": [],
    "🖊️": [],
    "🖌️": [],
    "🖍️": [],
    "📝": [],
    "🗑️": [],
    "📡": [],
    "🔭": [],
    "🔬": []
};
/*clothes and accessories*/
emojis[8] = {
    "👣": [],
    "👓": [],
    "🕶️": [],
    "🥽": [],
    "🥼": [],
    "👔": [],
    "👕": [],
    "👖": [],
    "🧣": [],
    "🧤": [],
    "🧥": [],
    "🧦": [],
    "👗": [],
    "👘": [],
    "👙": [],
    "👚": [],
    "👛": [],
    "👜": [],
    "👝": [],
    "🎒": [],
    "👞": [],
    "👟": [],
    "🥾": [],
    "🥿": [],
    "👠": [],
    "👡": [],
    "👢": [],
    "👑": [],
    "👒": [],
    "🎩": [],
    "🎓": [],
    "🧢": [],
    "⛑️": [],
    "💼": []
};
/*hands and parts of body*/
emojis[9] = {
    "👋": [],
    "🤚": [],
    "✋": [],
    "🖖": [],
    "👌": [],
    "✌️": [],
    "🤞": [],
    "🤟": [],
    "🤘": [],
    "🤙": [],
    "🤏": [],
    "👈": [],
    "👉": [],
    "👆": [],
    "👇": [],
    "☝️": [],
    "🖕": [],
    "👍": [],
    "👎": [],
    "✊": [],
    "👊": [],
    "🤛": [],
    "🤜": [],
    "👏": [],
    "🙌": [],
    "👐": [],
    "🤲": [],
    "🤝": [],
    "🙏": [],
    "✍️": [],
    "💪": [],
    "🦵": [],
    "🦶": [],
    "👂": [],
    "👃": [],
    "🧠": [],
    "🦷": [],
    "👀": [],
    "👁️": [],
    "👅": [],
    "👄": []
};
/*other*/
emojis[10] = {
    "💩": [],
    "💋": [],
    "💅": [],
    "🤳": [],
    "🦴": [],
    "🧳": [],
    "🌂": [],
    "☂️": [],
    "🧵": [],
    "🧶": [],
    "💄": [],
    "💍": [],
    "💥": [],
    "💫": [],
    "💦": [],
    "💨": [],
    "🐾": [],
    "🕸️": [],
    "🦠": [],
    "💐": [],
    "🌍": [],
    "🌎": [],
    "🌏": [],
    "🌐": [],
    "🌑": [],
    "🌓": [],
    "🌕": [],
    "🌗": [],
    "🌙": [],
    "🌛": [],
    "🌜": [],
    "☀️": [],
    "⭐": [],
    "☁️": [],
    "⛅": [],
    "⛈️": [],
    "🌤️": [],
    "🌥️": [],
    "🌦️": [],
    "🌧️": [],
    "🌨️": [],
    "🌩️": [],
    "🌪️": [],
    "🌫️": [],
    "🌈": [],
    "❄️": [],
    "☃️": [],
    "⛄": [],
    "☄️": [],
    "🔥": [],
    "💧": [],
    "🌊": [],
    "🎄": [],
    "🌻": [],
    "🌼": [],
    "🌷": [],
    "🌹": [],
    "🌹": [],
    "🌳": [],
    "🌴": [],
    "☘️": [],
    "🔑": [],
    "🗝️": [],
    "🔨": [],
    "⛏️": [],
    "🔒": [],
    "🔓": [],
    "🔏": [],
    "🔐": [],
    "🗡️": [],
    "⚔️": [],
    "🔫": [],
    "🧰": [],
    "🧲": [],
    "⛓️": [],
    "💉": [],
    "🧬": [],
    "🧪": [],
    "🛏️": [],
    "🚪": [],
    "🚽": [],
    "🚿": [],
    "🛁": [],
    "🧴": [],
    "🧷": [],
    "🧺": [],
    "🧻": [],
    "🧼": [],
    "🧽": [],
    "🧯": [],
    "🚬": [],
    "⚰️": [],
    "⚱️": [],
    "🗿": [],
    "🛡️": [],
    "⚙️": [],
    "⚖️": [],
    "🔗": [],
    "💀": [],
    "☠️": [],
    "🦻": [],
    "🦸": [],
    "🦸‍♀️": [],
    "🦹": [],
    "🦹‍♀️": [],
    "🧙": [],
    "🧙‍♀️": [],
    "🧚": [],
    "🧚‍♀️": [],
    "🧛": [],
    "🧛‍♀️": [],
    "🧜": [],
    "🧜‍♀️": [],
    "🧝": [],
    "🧝‍♀️": [],
    "🧞‍♂️": [],
    "🧞": [],
    "🕵️": [],
    "💂": [],
    "💂‍♀️": [],
    "👮": [],
    "👮‍♀️": [],
    "👨‍🚒": [],
    "👩‍🚒": [],
    "👨‍‍✈️": [],
    "👩‍✈️": [],
    "👨‍‍💻": [],
    "👩‍💻": [],
    "👨‍‍🎤": [],
    "👩‍🎤": [],
    "👨‍‍🎨": [],
    "👩‍🎨": [],
    "👷‍♂️": [],
    "👷‍♀️": [],
    "💑": [],
    "👨‍❤️‍👨": [],
    "👩‍❤️‍👩": []
};