// descriptions gave on Emojipedia.org
var titles = ["🔍", "😀", "🙋", "🦊", "🅰️", "🍎", "🏳️‍🌈", "🏊", "✈️", "🖱️", "👗", "🖐️", "🛎️"];
var emojis = [];

/*search*/
emojis[0] = {};
/*smileys*/
emojis[1] = {
    "😀": [":)", "Grinning Face", "Happy Face", "Smiley Face"],
    "😃": [":D", "Grinning Face with Big Eyes", "Happy Face", "Smiley Face", "Smiling Face with Open Mouth"],
    "😄": ["Grinning Face with Smiling Eyes", "Happy Face", "Smiley Face", "Grinning Face With Squinting Eyes", "Smiling Face with Open Mouth and Smiling Eyes"],
    "😁": ["Beaming Face with Smiling Eyes", "Grinning Face with Smiling Eyes"],
    "😆": ["xD", "><", "Grinning Squinting Face", "Big Grin", "Closed-Eyes Smile", "Laughing", "Grinning Face With Tightly Closed Eyes", "Smiling Face with Open Mouth and Tightly-Closed Eyes"],
    "😅": ["Grinning Face with Sweat", "Exercise", "Happy Sweat", "Grinning Face With Squinting Eyes and Sweat Drop", "Smiling Face with Open Mouth and Cold Sweat"],
    "🤣": ["ROFL", "Rolling on the Floor Laughing"],
    "😂": ["Face with Tears of Joy", "Laughing", "Laughing Crying", "Laughing Tears", "LOL"],
    "🙂": [":)", "Slightly Smiling Face", "Slightly Happy", "This Is Fine"],
    "🙃": ["Upside-Down Face", "Sarcasm", "Silly", "Upside Down Face"],
    "😉": [";)", "Winking Face", "Wink", "Wink Face", "Winky Face"],
    "😊": ["^^", "Smiling Face with Smiling Eyes", "Happy Face", "Smile", "Smiley Face"],
    "😇": ["Smiling Face with Halo", "Angel", "Halo"],
    "🥰": ["Smiling Face with Hearts", "In Love Face", "Smiling Face with Smiling Eyes and Three Hearts"],
    "😍": ["*.*", "Smiling Face with Heart-Eyes", "Heart Eyes", "Heart Face", "Smiling Face with Heart-Shaped Eyes"],
    "🤩": ["Star-Struck", "Excited", "Star Eyes", "Starry Eyed", "Wow Face", "Face With Starry Eyes", "Grinning Face with Star Eyes"],
    "😘": [":*", ":-*", "Face Blowing a Kiss", "Blow A Kiss", "Blowing Kiss", "Kissing", "Face Throwing a Kiss"],
    "😗": [":*", ":-*", "Kissing Face", "Duck Face", "Kissy Face", "Whistling"],
    "☺️": ["Smiling Face", "Happy Face", "Smiley Face", "Smiling", "White Smiling Face"],
    "😚": ["Kissing Face with Closed Eyes", "Kiss Face", "Kissy Face"],
    "😙": ["Kissing Face with Smiling Eyes", "Kiss Face", "Kissy", "Whistle", "Whistling"],
    "😋": ["Face Savoring Food", "Goofy", "Hungry", "Smiling Face Licking Lips", "Face Savouring Delicious Food"],
    "😛": [":P", "Face with Tongue", "Cheeky", "Tongue Face", "Tongue-Out", "Face with Stuck-Out Tongue"],
    "😜": [";P", "Winking Face with Tongue", "Crazy", "Crazy Face", "Winking Face With Stuck-Out Tongue", "Face with Stuck-Out Tongue and Winking Eye"],
    "🤪": ["Zany Face", "Crazy Eyes", "Excited", "Wild", "Goofy Face", "Grinning Face with One Large and One Small Eye"],
    "😝": ["xP", "Squinting Face with Tongue", "Tongue Out", "Face With Stuck Out Tongue and Tightly-Closed Eyes", "Face with Stuck-Out Tongue and Tightly-Closed Eyes"],
    "🤑": ["$", "Money-Mouth Face", "Dollar Sign Eyes", "Money Face", "Rich"],
    "🤗": ["Hugging Face", "Hug", "Hugging", "Hugs", "Happy Face With Hugging Hands"],
    "🤭": ["Oops", "Face with Hand Over Mouth", "Smiling Face with Smiling Eyes and Hand Covering Mouth"],
    "🤫": ["Shh", "Shush", "Shushing Face", "Hush", "Quiet", "Silence", "Silent", "Face with Finger Covering Closed Lips"],
    "🤔": ["What", "?", "Hmm", "Thinking Face", "Chin Thumb", "Thinker", "Throwing Shade"],
    "🤐": ["Zip", "Zipper-Mouth Face", "Lips Sealed", "Sealed Lips", "Zip It", "Face With a Zipper Mouth"],
    "🤨": ["Face with Raised Eyebrow", "Colbert", "The Rock", "Face With Raised Eyebrow", "Face with One Eyebrow Raised"],
    "😐": [":|", "Neutral Face", "Face With Straight Mouth", "Straight Faced"],
    "😑": ["-_-", "Expressionless Face", "Face With Straight Mouth", "Straight Face"],
    "😶": ["Face Without Mouth", "Blank Face", "Mouthless", "Silence", "Silent"],
    "😏": ["Smirking Face", "Flirting", "Sexual Face", "Smug Face", "Suggestive Smile"],
    "😒": ["Unamused Face", "Dissatisfied", "Meh", "Side-Eye", "Unimpressed"],
    "🙄": ["Face with Rolling Eyes", "Eye Roll"],
    "😬": ["Grimacing Face", "Awkward", "Eek", "Foot In Mounth", "Nervous", "Snapchat Mutual #1 Best Friend"],
    "🤥": ["Lying Face", "Liar", "Long Nose", "Pinocchio"],
    "😌": ["Relieved Face", "Content", "Pleased"],
    "😔": ["Sorry", "Pensive Face", "Pensive", "Sad", "Sadface", "Sorrowful", "Sad Pensive Face"],
    "😪": ["Sleepy Face", "Side-Tear", "Snot Bubble", ],
    "🤤": ["Saliva", "Drooling Face", "Drool"],
    "😴": ["Zzz", "Sleeping Face", "Sleep Face", "Snoring", "Zzz Face"],
    "🥱": ["Yawning Face"],
    "😷": ["Face with Medical Mask", "Coronavirus", "COVID-19", "Mask Face", "Surgical Mask"],
    "🤒": ["Face with Thermometer", "Ill", "Sick"],
    "🤕": ["Face with Head-Bandage", "Bandaged Head", "Clumsy", "Injured"],
    "🤢": ["Nauseated Face", "Disgust", "Green Face", "Vomit"],
    "🤮": ["Face Vomiting", "Spew", "Bleah", "Bleurgh", "Yuk", "Yuck", "Ew", "Spew", "Throwing Up", "Vomit", "Face with Open Mouth Vomiting"],
    "🤧": ["Sneezing Face", "Gesundheit"],
    "🥵": ["Hot Face", "Overheated Face"],
    "🥶": ["Cold Face", "Cool", "Chill", "Freezing Face"],
    "🥴": ["Woozy Face", "Drunk Face", "Face with Uneven Eyes and Wavy Mouth"],
    "😵": ["Dizzy Face", "Cross Eyes Face", "Spiral Eyes Face"],
    "🤯": ["Exploding Head", "Mind Blown", "Shocked Face with Exploding Head"],
    "🤠": ["Cowboy Hat Face", "Cowboy", "Cowboy Face", "Face with Cowboy Hat"],
    "🥳": ["Partying Face", "Party Face", "Face with Party Horn and Party Hat"],
    "😎": ["Smiling Face with Sunglasses", "Cool", "Mutual Best Friends (Snapchat)", "Sunglasses"],
    "🤓": ["Nerd Face", "Nerdy"],
    "🧐": ["Face with Monocle"],
    "😕": [":/", ":S", "Confused Face", "Nonplussed", "Puzzled"],
    "😟": [":(", "Worried Face", "Sad", "Sadface"],
    "🙁": [":(", "Slightly Frowning Face", "Slightly Sad"],
    "☹️": [":(", "Frowning Face", "Megafrown", "White Frowning Face"],
    "😮": [":O", "Wow", "Oh my!", "Face with Open Mouth", "Open Mouth", "Surprised Face With Open Mouth"],
    "😯": [":O", "Hushed Face", "Surprise", "Surprised Face"],
    "😲": [":O", "Wow", "Astonished Face", "Drunk Face", "Gasping Face", "Shocked Face"],
    "😳": [":$", "Flushed Face", "Blushing Face", "Embarrassed", "Shame", "Face With Wide Open Eyes"],
    "🥺": [":(", "Pleading Face", "Begging", "Glossy Eyes", "Simp", "Face with Pleading Eyes"],
    "😦": ["D:", "Frowning Face with Open Mouth", "Yawning"],
    "😨": ["D:", "Fearful Face", "Scared", "Surprised"],
    "😰": ["Anxious Face with Sweat", "Blue Face", "Concerned Face", "Nervous Face", "Face with Open Mouth and Cold Sweat"],
    "😥": [":'(", "Sad but Relieved Face", "Eyebrow Sweat", "Disappointed but Relieved Face"],
    "😢": [":'(", "Crying Face", "Crying", "Tear"],
    "😭": ["Loudly Crying Face", "Bawling", "Crying", "Sad Tears", "Sobbing"],
    "😱": ["Face Screaming in Fear", "Home Alone", "Scream", "Screaming Face"],
    "😖": ["Confounded Face", "Quivering Mouth", "Scrunched Face"],
    "😣": ["Persevering Face", "Helpless Face", "Scrunched Eyes"],
    "😞": [":(", "Disappointed Face", "Sad", "Sadface"],
    "😓": ["Downcast Face with Sweat", "Hard Work", "Sad Sweat Face", "Face with Cold Sweat"],
    "😩": ["Weary Face", "Distraught Face", "Wailing"],
    "😫": ["Tired Face", "Exhausted", "Fed Up", "Distraught Face"],
    "😤": ["Face with Steam From Nose", "Airing of Grievances", "Frustrated", "Mad Face", "Steaming", "Huffing With Anger Face"],
    "😡": ["Pouting Face", "Angry Face", "Grumpy Face", "Mad Face", "Red Face"],
    "😠": ["Angry Face", "Angry", "Grumpy Face"],
    "🤬": ["@#$%&!", "Face with Symbols on Mouth", "Cursing", "Cussing", "Grawlix", "Swearing", "Face With Symbols Over Mouth", "Serious Face with Symbols Covering Mouth"],
    "😈": ["Smiling Face with Horns", "Devil", "Devil Horns", "Happy Devil", "Purple Devil", "Red Devil"],
    "👿": ["Angry Face with Horns", "Devil", "Devil Horns", "Purple Devil", "Purple Goblin", "Sad Devil", "Imp"],
    "🤡": ["Clown Face", "Creepy Clown", "Evil Clown", "Scary Clown"],
    "👽": ["Alien", "ET"],
    "👾": ["Alien Monster", "Space Invader", "Video Game Monster"],
    "🤖": ["Robot", "Robot Face"],
    "👹": ["Ogre", "Mask Face", "Oni", "Red Monster", "Japanese Ogre"],
    "👻": ["Ghost", "Halloween"],
    "👶": ["Baby", "Child", "Toddler"],
    "🧒": ["Child", "Gender Neutral Child"],
    "👧": ["Girl"],
    "🧑": ["Person", "Gender Neutral Adult", "Adult"],
    "👱": ["Person: Blond Hair", "Blond", "Blonde", "Blond Man", "Person with Blond Hair", "Man With Blonde Hair"],
    "👨": ["Man", "Male", "Moustache Man"],
    "🧔": ["Man: Beard", "Beard", "Bearded Man", "Bearded Person"],
    "👨‍🦰": ["Man: Red Hair", "Ginger Man", "Man Redhead", "Man With Red Hair"],
    "👨‍🦱": ["Man: Curly Hair", "Man With Curly Hair"],
    "👨‍🦳": ["Man: White Hair", "Man With Gray Hair"],
    "👨‍🦲": ["Man: Bald", "Man With No Hair"],
    "👩": ["Woman", "Female", "Lady", "Yellow Woman"],
    "👩‍🦰": ["Woman: Red Hair", "Ginger Woman", "Woman Redhead", "Woman With Red Hair"],
    "👩‍🦱": ["Woman: Curly Hair", "Woman With Curly Hair"],
    "👩‍🦳": ["Woman: White Hair", "Woman With Gray Hair"],
    "👩‍🦲": ["Woman: Bald", "Woman With No Hair"],
    "👱‍♀️": ["Woman: Blond Hair", "Woman With Blonde Hair"],
    "👱‍♂️": ["Man: Blond Hair", "Man With Blonde Hair"],
    "🧓": ["Older Person", "Gender Neutral Older Adult"],
    "👴": ["Old Man", "Elderly Man", "Grandpa", "Older Man"],
    "👵": ["Old Woman", "Elderly Woman", "Grandma", "Nanna", "Old Lady", "Older Woman"],
    "👼": ["Baby Angel", "Angel", "Cherub", "Cupid", "Putto"],
    "🎅": ["Santa Claus", "Saint Nicholas", "Sinterklaas", "Father Christmas"],
    "🤶": ["Mrs. Claus", "Mrs Claus", "Mother Christmas"],
    "🤴": ["Prince"],
    "👸": ["Princess", "Blonde Girl", "Girl With Crown", "Girl With Tiara"],
    "👳": ["Person Wearing Turban", "Arab", "Muslim", "Sikh", "Turban", "Man with Turban"],
    "👳‍♂️": ["Man Wearing Turban"],
    "👳‍♀️": ["Woman Wearing Turban"],
    "👲": ["Person With Skullcap", "Asian Man", "Man With Chinese Cap", "Man with Gua Pi Mao"],
    "🧕": ["Woman with Headscarf", "Hijab", "Person with Headscarf"],
    "🤵": ["Person in Tuxedo", "Groom", "Man In Suit", "Man in Tuxedo"],
    "👰": ["Person With Veil", "Bride", "Bride with Veil"],
    "🤰": ["Pregnant Woman", "Pregnancy", "Pregnant Lady"],
    "🤱": ["Breast-Feeding", "Breastfeeding"]
};
/*people*/
emojis[2] = {
    "": []
};
/*animals*/
emojis[3] = {
    "😺": [":)", "Grinning Cat", "Happy Cat", "Smiling Cat", "Happy Cat Face", "Smiling Cat Face with Open Mouth"],
    "😸": [":D", "Grinning Cat with Smiling Eyes", "Grinning Cat", "Happy Cat", "Grinning Cat Face"],
    "😹": [":')", "Cat with Tears of Joy", "Happy Tears Cat", "Laughing Cat", ],
    "😻": ["*.*", "Smiling Cat with Heart-Eyes", "Heart Eyes Cat", "Loving Cat", "Smiling Cat Face with Heart-Shaped Eyes"],
    "😼": ["Cat with Wry Smile", "Smirking Cat", "Smirking Cat Face", "Cat Face with Wry Smile"],
    "😽": [":*", "Kissing Cat", "Kissing Cat Face", "Kissing Cat Face with Closed Eyes"],
    "🙀": [":O", "Weary Cat", "Scared Cat", "Screaming Cat", "Cat Face Screaming in Fear", "Weary Cat Face"],
    "😿": [":'(", "Crying Cat", "Sad Cat", "Crying Cat Face"],
    "😾": ["Pouting Cat", "Grumpy Cat", "Pouting Cat Face"],
    "🙈": ["Monkey", "See-No-Evil Monkey", "Mizaru", "Monkey Covering Eyes"],
    "🙉": ["Monkey", "Hear-No-Evil Monkey", "Kikazaru", "Monkey Covering Ears"],
    "🙊": ["Monkey", "Speak-No-Evil Monkey", "Iwazaru", "Monkey Covering Mouth", "No Speaking"],
    "🐵": ["Monkey", "Monkey Face", "Monkey Head"],
    "🐒": ["Monkey", "Cheeky Monkey"],
    "🦍": ["Gorilla"],
    "🐶": ["Dog Face", "Dog", "Puppy"],
    "🐕": ["Dog", "Doggo", "Akita Inu"],
    "🐩": ["Poodle", "Dog", "Miniature Poodle", "Standard Poodle", "Toy Poodle"],
    "🐺": ["Wolf", "Wolf Face"],
    "🦊": ["Fox", "Fox Face"],
    "🦝": ["Raccoon"],
    "🐱": [":3", "Cat Face", "Kitten", "Kitty"],
    "🐈": ["Cat", "Domestic Cat", "Feline", "Housecat"],
    "🦁": ["Lion", "Lion Face"],
    "🐯": ["Tiger Face", "Cute Tiger"],
    "🐅": ["Tiger", "Bengal Tiger"],
    "🐆": ["Leopard", "African Leopard", "Jaguar"],
    "🐴": ["Horse Face", "Horse Head"],
    "🐎": ["Horse", "Galloping Horse", "Racehorse"],
    "🦄": ["Unicorn", "Unicorn Face"],
    "🦓": ["Zebra", "Zebra Face"],
    "🦌": ["Deer", "Buck", "Reindeer", "Stag"],
    "🐮": ["Cow Face", "Cow", "Happy Cow"],
    "🐂": ["Ox", "Bull", "Bullock", "Oxen", "Steer"],
    "🐃": ["Water Buffalo", "Buffalo", "Domestic Water Buffalo"],
    "🐄": ["Cow", "Dairy Cow"],
    "🐷": ["Pig Face", "Pig", "Pig Head"],
    "🐖": ["Pig", "Hog", "Sow"],
    "🐗": ["Boar", "Warthog", "Wild Boar", "Wild Pig"],
    "🐽": ["Pig Nose"],
    "🐏": ["Ram", "Sheep"],
    "🐑": ["Ewe", "Lamb", "Sheep"],
    "🐐": ["Goat"],
    "🐪": ["Camel", "Arabian Camel", "Dromedary Camel", "One-Bump Camel"],
    "🐫": ["Two-Hump Camel", "Asian Camel", "Bactrian Camel"],
    "🦙": ["Llama", "Alpaca"],
    "🦒": ["Giraffe", "Giraffe Face"],
    "🐘": ["Elephant"],
    "🦏": ["Rhinoceros", "Rhino"],
    "🦛": ["Hippopotamus", "Hippo"],
    "🐭": ["Mouse Face", "Mouse"],
    "🐁": ["Mouse", "Dormouse", "Rodent", "Mice"],
    "🐀": ["Rat", "Rodent"],
    "🐹": ["Hamster", "Hamster Face"],
    "🐰": ["Rabbit Face", "Easter Bunny"],
    "🐇": ["Rabbit", "Bunny", "Bunny Rabbit"],
    "🐿️": ["Chipmunk", "Squirrel"],
    "🦔": ["Hedgehog"],
    "🦇": ["Bat", "Batman"],
    "🐻": ["Bear", "Bear Face", "Teddy Bear"],
    "🐨": ["Koala", "Koala Face"],
    "🐼": ["Panda", "Panda Face"],
    "🦘": ["Kangaroo", "Roo"],
    "🦡": ["Badger"],
    "🦃": ["Turkey", "Thanksgiving Turkey", "Wild Turkey"],
    "🐔": ["Chicken", "Hen"],
    "🐓": ["Cock", "Rooster", "Cockerel"],
    "🐣": ["Hatching Chick", "Baby Chicken", "Chick Hatching"],
    "🐤": ["Baby Chick", "Yellow Bird"],
    "🐥": ["Front-Facing Baby Chick", "Baby Chick", "Standing Chick"],
    "🐦": ["Bird"],
    "🐧": ["Penguin"],
    "🕊️": ["Dove", "Dove of Peace"],
    "🦅": ["Eagle", "Bald Eagle"],
    "🦆": ["Duck"],
    "🦢": ["Swan"],
    "🦉": ["Owl"],
    "🦚": ["Peacock"],
    "🦜": ["Parrot"],
    "🐸": ["Frog", "Toad", "Frog Face"],
    "🐊": ["Crocodile", "Alligator", "Croc"],
    "🐢": ["Turtle", "Tortoise"],
    "🦎": ["Lizard", "Gecko"],
    "🐍": ["Snake", "Serpent"],
    "🐲": ["Dragon Face", "Dragon Head"],
    "🐉": ["Dragon"],
    "🦕": ["Sauropod", "Brachiosaurus", "Brontosaurus", "Dinosaur"],
    "🦖": ["T-Rex", "Tyrannosaurus Rex"],
    "🐳": ["Spouting Whale", "Cute Whale"],
    "🐋": ["Whale"],
    "🐬": ["Dolphin"],
    "🐟": ["Fish", "Freshwater Fish"],
    "🐠": ["Tropical Fish", "Fish", "Yellow-Blue Fish"],
    "🐡": ["Blowfish", "Fugu", "Pufferfish"],
    "🦈": ["Shark", "Great White Shark"],
    "🐙": ["Octopus"],
    "🐚": ["Spiral Shell", "Seashell", "Shell"],
    "🐌": ["Snail", "Slug", "Garden Snail"],
    "🦋": ["Butterfly"],
    "🐛": ["Bug", "Caterpillar", "Insect"],
    "🐜": ["Ant", "Bug", "Insect"],
    "🐝": ["Honeybee", "Bee", "Bumblebee"],
    "🐞": ["Lady Beetle", "Ladybird", "Ladybug", "Bug"],
    "🦗": ["Cricket", "Grasshopper"],
    "🕷️": ["Spider"],
    "🦂": ["Scorpion"],
    "🦟": ["Mosquito"],
    "🦀": ["Crab"],
    "🦞": ["Lobster"],
    "🦐": ["Shrimp", "Prawn"],
    "🦑": ["Squid"]
};
/*symbols*/
emojis[4] = {
    "💘": ["Heart with Arrow", "Cupid Arrow", "Lovestruck"],
    "💝": ["Heart with Ribbon", "Chocolate Box", "Gift Box", "Gift Heart"],
    "💖": ["Sparkling Heart", "Sparkle Heart", "Sparkly Heart", "Stars Heart"],
    "💗": ["Growing Heart", "Multiple Heart", "Triple Heart"],
    "💓": ["Beating Heart", "Heart Alarm", "Heartbeat", "Wifi Heart"],
    "💞": ["Revolving Hearts", "Two Hearts"],
    "💕": ["Two Hearts", "Small Hearts", "Two Pink Hearts"],
    "💟": ["Heart Decoration"],
    "❣️": ["Heart Exclamation", "Heart Above Dot", "Red Heart As an Exclamation Mark", "Heavy Heart Exclamation Mark Ornament"],
    "💔": ["Broken Heart", "Breaking Heart", "Brokenhearted", "Heart Broken"],
    "❤️": ["I Love You", "Red Heart", "Heart", "Love Heart", "Red Heart"],
    "🧡": ["Orange Heart"],
    "💛": ["Yellow Heart", "#1 BF Snapchat", "Gold Heart"],
    "💚": ["Green Heart", "Jealous Heart"],
    "💙": ["Blue Heart"],
    "💜": ["Purple Heart"],
    "🖤": ["Black Heart", "Dark Heart"],
    "🤍": ["White Heart"],
    "🤎": ["Brown Heart"],
    "💯": ["Hundred Points", "100", "%", "Keep It 100", "Perfect Score", "Hundred Points Symbol"],
    "💬": ["Speech Balloon", "Chat Bubble", "Speech Bubble"],
    "💤": ["Zzz", "Bedtime", "Boring", "Sleep", "Sleeping Sign", "Sleeping Symbol"],
    "♠️": ["Spade Suit", "Spades", "Black Spade Suit"],
    "♥️": ["Heart Suit", "Card With Heart", "Hearts", "Black Heart Suit"],
    "♦️": ["Diamond Suit", "Diamonds", "Black Diamond Suit"],
    "♣️": ["Club Suit", "Clubs", "Black Club Suit"],
    "🏧": ["ATM Sign", "ATM", "Automated Telleer Machine"],
    "🎵": ["Musical Note", "Beamed Pair Of Eighth Notes", "Beamed Pair Of Quavers", "Music Note"],
    "🎶": ["Musical Notes", "Music", "Music Notes", "Singing", "Multiple Musical Notes"],
    "🔔": ["Bell", "Liberty Bell", "Ringer", "Wedding Bell"],
    "🔕": ["Bell with Slash", "Notifications", "Ringer Disabled", "Muted Bell", "Bell with Cancellation Stroke"],
    "🔈": ["Speaker Low Volume", "Volume", "Speaker"],
    "🔉": ["Speaker Medium Volume", "Reduce Volume", "Speaker With Medium Volume", "Speaker with One Sound Wave"],
    "🔊": ["Speaker High Volume", "Increase Volume", "Speaker with Three Sound Waves"],
    "🔇": ["Muted Speaker", "Mute Volume", "Speaker with Cancellation Stroke"],
    "⛔": ["No Entry"],
    "🚫": ["Prohibited", "Banned", "Circle Backslash", "No", "Red Circle Crossed", "Restricted", "No Entry Sign"],
    "🚳": ["No Bicycles", "No Bikes Sign"],
    "🚭": ["No Smoking", "No Smoking Symbol"],
    "🚯": ["No Littering", "Do Not No Litter Symbol"],
    "🚱": ["Non-Potable Water", "No Water", "No Drinking Water", "Non-Potable Water Symbol"],
    "🚷": ["No Pedestrians", "No People", "No Walking"],
    "🔞": ["No One Under Eighteen", "NSFW", "No One Under Eighteen Symbol", "18"],
    "☢️": ["Radioactive", "International Radiation Symbol", "Nuclear", "Radioactive Sign"],
    "☣️": ["Biohazard", "Biohazard Sign"],
    "⬆️": ["Up Arrow", "Arrow Pointing Up", "Upwards Black Arrow"],
    "↗️": ["Up-Right Arrow", "Diagonal Up-Right Arrow", "North East Arrow"],
    "➡️": ["Right Arrow", "Arrow Pointing Right", "Black Rightwards Arrow"],
    "↘️": ["Down-Right Arrow", "Diagonal Down-Right Arrow", "South East Arrow"],
    "⬇️": ["Down Arrow", "Arrow Pointing Down", "Downwards Black Arrow"],
    "↙️": ["Down-Left Arrow", "Diagonal Down-Left Arrow", "South West Arrow"],
    "⬅️": ["Left Arrow", "Arrow Pointing Left", "Leftwards Black Arrow"],
    "↖️": ["Up-Left Arrow", "Diagonal Up-Left Arrow", "North West Arrow"],
    "↕️": ["Up-Down Arrow", "Vertical Arrows", "Up Down Arrow"],
    "↔️": ["Left-Right Arrow", "Horizontal Arrows", "Sideways Arrows", "Left Right Arrow"],
    "↩️": ["Right Arrow Curving Left", "Email Reply", "Left Curved Arrow", "Leftwards Arrow with Hook"],
    "↪️": ["Left Arrow Curving Right", "Email Forward", "Right Curved Arrow", "Rightwards Arrow with Hook"],
    "⤴️": ["Right Arrow Curving Up", "Arrow Pointing Rightwards Then Curving Upwards"],
    "⤵️": ["Right Arrow Curving Down", "Curved Down Arrow", "Arrow Pointing Rightwards Then Curving Downwards"],
    "🔃": ["Clockwise Vertical Arrows", "Clockwise Downwards and Upwards Open Circle Arrows"],
    "🔄": ["Counterclockwise Arrows Button", "Refresh", "Rotate", "Switch", "Counter-Clockwise Arrows", "Anticlockwise Downwards and Upwards Open Circle Arrows"],
    "🔙": ["Back Arrow", "Back", "Back with Leftwards Arrow Above"],
    "🔚": ["End Arrow", "End", "End with Leftwards Arrow Above"],
    "🔛": ["On! Arrow", "On", "On with Exclamation Mark with Left Right Arrow Above"],
    "🔜": ["Soon Arrow", "Soon", "Soon with Rightwards Arrow Above"],
    "🔝": ["Top Arrow", "Top", "Top with Upwards Arrow Above"],
    "🛐": ["Place of Worship", "Religious Building"],
    "⚛️": ["Atom Symbol"],
    "🕉️": ["Om", "Aumkara", "Omkara", "Pranava", "Om Symbol"],
    "✡️": ["Star of David", "Magen David"],
    "☸️": ["Wheel of Dharma", "Helm"],
    "☯️": ["Yin Yang"],
    "✝️": ["Latin Cross", "Christian Cross"],
    "☦️": ["Orthodox Cross"],
    "☪️": ["Star and Crescent"],
    "☮️": ["Peace Symbol", "Peace Sign"],
    "🕎": ["Menorah", "Candelabrum", "Candles", "Chanukiah", "Menorah", "Menorah with Nine Branches"],
    "🔯": ["Dotted Six-Pointed Star", "Six Pointed Star with Middle Dot"],
    "♈": ["Aries", "Zodiac"],
    "♉": ["Taurus", "Zodiac"],
    "♊": ["Gemini", "Zodiac"],
    "♋": ["Cancer", "Zodiac"],
    "♌": ["Leo", "Zodiac"],
    "♍": ["Virgo", "Zodiac"],
    "♎": ["Libra", "Zodiac"],
    "♏": ["Scorpio", "Scorpius", "Zodiac"],
    "♐": ["Sagittarius", "Zodiac"],
    "♑": ["Capricorn", "Zodiac"],
    "♒": ["Aquarius", "Zodiac"],
    "♓": ["Pisces", "Zodiac"],
    "⛎": ["Ophiuchus", "Zodiac"],
    "🔀": ["Shuffle Tracks Button", "Twisted Rightwards Arrows"],
    "🔁": ["Repeat Button", "Loop Symbol", "Retweet", "Clockwise Rightwards and Leftwards Open Circle Arrows"],
    "🔂": ["Repeat Single Button", "Circle Arrows With Number 1", "Loop Once Symbol", "Repeat Single Track Symbol", "Clockwise Rightwards and Leftwards Open Circle Arrows with Circled One Overlay"],
    "▶️": ["Play Button", "Right Triangle", "Right-Pointing Triangle", "Black Right-Pointing Triangle"],
    "◀️": ["Reverse Button", "Left Triangle", "Left-Pointing Triangle", "Black Left-Pointing Triangle"],
    "🔼": ["Upwards Button", "Up Triangle", "Up-Pointing Triangle", "Up-Pointing Small Red Triangle"],
    "🔽": ["Downwards Button", "Down Triangle", "Down-Pointing Triangle", "Down-Pointing Small Red Triangle"],
    "⏩": ["Fast-Forward Button", "Fast Forward", "Fast Forward Symbol", "Black Right-Pointing Double Triangle"],
    "⏪": ["Fast Reverse Button", "Rewind", "Rewind Symbol", "Black Left-Pointing Double Triangle"],
    "⏫": ["Fast Up Button", "Up-Pointing Double Triangle", "Black Up-Pointing Double Triangle"],
    "⏬": ["Fast Down Button", "Down-Pointing Double Triangle", "Black Down-Pointing Double Triangle"],
    "⏹️": ["Stop Button", "Stop", "Stop Symbol", "Black Square for Stop"],
    "⏏️": ["Eject Button", "Eject Symbol"],
    "🎦": ["Cinema", "Cinema Screen", "Movies", "Film", "Cinema Symbol", "Recording"],
    "📶": ["Antenna Bars", "Reception Bars", "Signal Strength", "Stairs", "Signal Strength Symbol", "Antenna with Bars"],
    "✖️": ["Multiply", "Multiplication Symbol", "Heavy Multiplication X"],
    "➕": ["Plus", "Plus Symbol", "Heavy Plus Sign"],
    "➖": ["Minus", "Minus Symbol", "Heavy Minus Sign"],
    "➗": ["Divide", "Division Symbol", "Heavy Division Sign"],
    "♾️": ["Infinity", "Permanent Paper Sign"],
    "‼️": ["Double Exclamation Mark", "Red Double Exclamation Mark"],
    "⁉️": ["Exclamation Question Mark", "Red Exclamation Mark and Question Mark"],
    "❓": ["Question Mark", "Red Question Mark", "Black Question Mark Ornament"],
    "❔": ["White Question Mark", "White Question Mark", "White Question Mark Ornament"],
    "❗": ["Exclamation Mark", "Red Exclamation Mark", "Heavy Exclamation Mark Symbol"],
    "❕": ["White Exclamation Mark", "White Exclamation Mark Ornament"],
    "⭕": ["Hollow Red Circle", "Circle", "Correct", "Red Circle", "Circle Mark", "Heavy Large Circle"],
    "☑️": ["Check Box with Check", "V", "Checkbox", "Check Mark In Box", "Ballot Box with Check"],
    "✔️": ["Check Mark", "V", "Check", "Tick", "Checkmark", "Heavy Check Mark"],
    "❌": ["Cross Mark", "Cross", "X"],
    "✅": ["Check Mark Button", "V", "Green Check Mark", "Green Tick", "Check Mark", "White Heavy Check Mark"],
    "❎": ["Cross Mark Button", "Cross", "X", "X Mark", "Negative Squared Cross Mark"],
    "#️⃣": ["Keycap Number Sign", "#", "Hash Key", "Hashtag", "Octothorpe", "Pound Key", "Number Sign"],
    "0️⃣": ["Keycap Digit Zero", "Number 0"],
    "1️⃣": ["Keycap Digit One", "Number 1"],
    "2️⃣": ["Keycap Digit Two", "Number 2"],
    "3️⃣": ["Keycap Digit Three", "Number 3"],
    "4️⃣": ["Keycap Digit Four", "Number 4"],
    "5️⃣": ["Keycap Digit Five", "Number 5"],
    "6️⃣": ["Keycap Digit Six", "Number 6"],
    "7️⃣": ["Keycap Digit Seven", "Number 7"],
    "8️⃣": ["Keycap Digit Eight", "Number 8"],
    "9️⃣": ["Keycap Digit Nine", "Number 9"],
    "🔟": ["Keycap: 10", "10", "Number 10", "Keycap Ten"],
    "🔠": ["Input Latin Uppercase", "ABCD", "Uppercase", "Input Symbol for Uppercase Letters", "Input Symbol for Latin Capital Letters"],
    "🔡": ["Input Latin Lowercase", "abcd", "Lowercase", "Input Symbol for Lowercase Letters", "Input Symbol for Latin Small Letters"],
    "🔢": ["Input Numbers", "1234", "Numbers", "Numeric Input", "Input Symbol for Numbers"],
    "🔤": ["Input Latin Letters", "abc", "Alphabet", "Letters", "Input Symbol for Letters", "Input Symbol for Latin Letters"],
    "🅰️": ["A Button (Blood Type)", "Blood Type A", "Letter A", "Negative Squared Latin Capital Letter A"],
    "🆎": ["AB Button (Blood Type)", "Letters AB", "Blood Type AB", "Negative Squared AB"],
    "🅱️": ["B Button (Blood Type)", "Letter B", "Blood Type B", "Negative Squared Latin Capital Letter B"],
    "🆑": ["CL Button", "Clear", "Clear Button", "CL Sign", "Squared CL"],
    "🆒": ["Cool Button", "Cool Square", "Cool Sign", "Squared Cool"],
    "🆓": ["Free Button", "Free", "Free Sign", "Squared Free"],
    "ℹ️": ["Information", "Info", "Lowercase I", "Tourist Information", "Information Source"],
    "🆔": ["ID Button", "ID", "Identification", "Identification Sign", "Squared ID"],
    "🆕": ["New Button", "New", "New Sign", "Squared New"],
    "🅾️": ["O Button (Blood Type)", "Blood Type O", "0", "Negative Squared Latin Capital Letter O"],
    "🆗": ["OK Button", "OK", "Okay", "Square", "OK Sign", "Squared OK"],
    "🅿️": ["P Button", "Parking Sign", "Negative Squared Latin Capital Letter P"],
    "🆘": ["SOS Button", "Distress Signal", "Emergency", "SOS", "SOS Sign", "Squared SOS"],
    "🆙": ["Up! Button", "Level Up", "Up", "Up Sign", "Squared Up with Exclamation Mark"],
    "🆚": ["Vs Button", "Squared Vs"],
    "🔴": ["Red Circle", "Large Red Circle"],
    "🔵": ["Blue Circle", "Large Blue Circle"],
    "⚫": ["Black Circle", "Medium Black Circle"],
    "⚪": ["White Circle", "Medium White Circle"],
    "⬛": ["Black Large Square"],
    "⬜": ["White Large Square"],
    "🔶": ["Large Orange Diamond"],
    "🔷": ["Large Blue Diamond"],
    "🔸": ["Small Orange Diamond"],
    "🔹": ["Small Blue Diamond"],
    "🔺": ["Red Triangle Pointed Up", "Up-Pointing Red Triangle"],
    "🔻": ["Red Triangle Pointed Down", "Down-Pointing Red Triangle"],
    "🔳": ["White Square Button"],
    "🔲": ["Black Square Button"],
    "©️": ["Copyright", "Copyright Sign"],
    "®️": ["Registered", "Registered Sign"],
    "™️": ["Trade Mark", "TM", "Trademark", "Trade Mark Sign"]
};
/*food and drinks*/
emojis[5] = {
    "🍇": ["Grapes", "Grape"],
    "🍈": ["Melon", "Cantaloupe", "Honeydew", "Muskmelon"],
    "🍉": ["Watermelon"],
    "🍊": ["Tangerine", "Mandarin", "Orange"],
    "🍋": ["Lemon", "Lemonade"],
    "🍌": ["Banana", "Plantain"],
    "🍍": ["Pineapple"],
    "🥭": ["Mango"],
    "🍎": ["Red Apple", "Red Delicious Apple"],
    "🍏": ["Green Apple", "Golden Delicious Apple", "Granny Smith Apple"],
    "🍐": ["Pear"],
    "🍑": ["Peach", "Bottom", "Butt"],
    "🍒": ["Cherries", "Cherry", "Wild Cherry"],
    "🍓": ["Strawberry"],
    "🥝": ["Kiwi Fruit", "Chinese Gooseberry", "Kiwi", "Kiwifruit"],
    "🍅": ["Tomato"],
    "🥥": ["Coconut", "Cocoanut"],
    "🥑": ["Avocado"],
    "🍆": ["Eggplant", "Aubergine", "Phallic", "Purple Vegetable"],
    "🥔": ["Potato", "Baked Potato", "Idaho Potato"],
    "🥕": ["Carrot"],
    "🌽": ["Ear of Corn", "Corn", "Corn On The Cob", "Maize", "Ear of Maize"],
    "🌶️": ["Hot Pepper", "Chili Pepper", "Spicy"],
    "🥒": ["Cucumber", "Gherkin", "Pickle"],
    "🥬": ["Leafy Green", "Bok Choy", "Chinese Cabbage", "Cos Lettuce", "Romaine Lettuce", "Leafy Greens"],
    "🥦": ["Broccoli"],
    "🍄": ["Mushroom", "Shroom", "Toadstool"],
    "🥜": ["Peanuts", "Nuts"],
    "🌰": ["Chestnut", "Acorn", "Nut"],
    "🍞": ["Bread", "Loaf Of Bread"],
    "🥐": ["Croissant"],
    "🥖": ["Baguette Bread", "French Bread", "Baguette"],
    "🥨": ["Pretzel"],
    "🥯": ["Bagel"],
    "🥞": ["Pancakes", "Crêpes", "Hotcakes"],
    "🧀": ["Cheese Wedge", "Cheese"],
    "🍖": ["Meat on Bone", "BBQ", "Barbecue", "Manga Meat"],
    "🍗": ["Poultry Leg", "Drumstick", "Turkey Leg"],
    "🥩": ["Cut of Meat", "Meat", "Steak"],
    "🥓": ["Bacon", "Rashers"],
    "🍔": ["Hamburger", "Burger", "Cheeseburger"],
    "🍟": ["French Fries", "Chips", "Fries", "McDonald's Fries"],
    "🍕": ["Pizza", "Pepperoni Pizza", "Slice of Pizza"],
    "🌭": ["Hot Dog", "Hotdog", "Sausage"],
    "🥪": ["Sandwich"],
    "🌮": ["Taco"],
    "🌯": ["Burrito", "Wrap"],
    "🥙": ["Stuffed Flatbread", "Doner Kebab", "Gyro", "Shawarma", "Pita Sandwich"],
    "🍳": ["Cooking", "Breakfast", "Fried Egg", "Frying Pan"],
    "🥘": ["Shallow Pan of Food", "Paella", "Pan of Food"],
    "🍲": ["Pot of Food", "Bowl Of Food", "Soup", "Stew"],
    "🥣": ["Bowl with Spoon", "Cereal Bowl"],
    "🥗": ["Green Salad", "Salad"],
    "🍿": ["Popcorn", "Popping Corn"],
    "🧂": ["Salt", "Salt Shaker"],
    "🥫": ["Canned Food", "Can of Food", "Tin Can", "Tinned Food"],
    "🍱": ["Bento Box", "Lunch Box"],
    "🍘": ["Rice Cracker", "Cracker"],
    "🍙": ["Rice Ball", "Onigiri"],
    "🍚": ["Cooked Rice", "Boiled Rice", "Rice", "Bowl Of Rice", "Steamed Rice"],
    "🍛": ["Curry Rice", "Curry", "Indian Food", "Curry and Rice"],
    "🍜": ["Steaming Bowl", "Noodles", "Noodles With Chopsticks", "Ramen"],
    "🍝": ["Spaghetti", "Pasta"],
    "🍠": ["Roasted Sweet Potato", "Sweet Potato", "Yam"],
    "🍢": ["Oden", "Kebab", "Skewer"],
    "🍣": ["Sushi", "Sashimi", "Seafood"],
    "🍤": ["Fried Shrimp", "Fried Prawn", "Shrimp Tempura"],
    "🍥": ["Fish Cake with Swirl", "Fishcake", "Pink Swirl"],
    "🥮": ["Moon Cake", "Mooncake"],
    "🍡": ["Dango", "Dessert Stick", "Pink White Green Balls"],
    "🥟": ["Dumpling", "Empanada", "Pierogi"],
    "🥠": ["Fortune Cookie"],
    "🥡": ["Takeout Box", "Chinese Food Box", "Oyster Pail"],
    "🍦": ["Soft Ice Cream", "Mr. Whippy", "Soft Serve"],
    "🍧": ["Shaved Ice", "Snow Cone"],
    "🍨": ["Ice Cream", "Bowl Of Ice Cream", "Dessert"],
    "🍩": ["Doughnut", "Donut"],
    "🍪": ["Cookie", "Biscuit", "Chocolate Chip Cookie"],
    "🎂": ["Birthday Cake", "Birthday", "Cake", "Cake With Candles"],
    "🍰": ["Shortcake", "Cake", "Piece Of Cake", "Strawberry Shortcake"],
    "🧁": ["Cupcake", "Fairy Cake"],
    "🥧": ["Pie"],
    "🍫": ["Chocolate Bar", "Candy Bar", "Chocolate"],
    "🍬": ["Candy", "Lolly", "Sweet"],
    "🍭": ["Lollipop", "Sucker"],
    "🍮": ["Custard", "Creme Caramel", "Dessert", "Flan", "Pudding"],
    "🍯": ["Honey Pot", "Honey", "Pot"],
    "🍼": ["Baby Bottle", "Bottle Feeding"],
    "🥛": ["Glass of Milk", "Milk"],
    "☕": ["Hot Beverage", "Coffee", "Espresso", "Hot Chocolate", "Tea"],
    "🍵": ["Teacup Without Handle", "Green Tea", "Matcha", "Matcha Green Tea"],
    "🍶": ["Sake", "Bottle", "Rice Wine", "Sake Bottle and Cup"],
    "🍾": ["Bottle with Popping Cork", "Celebration", "Champagne", "Sparkling Wine"],
    "🍷": ["Wine Glass", "Alcohol", "Red Wine", "Wine"],
    "🍸": ["Cocktail Glass", "Cocktail", "Martini"],
    "🍹": ["Tropical Drink", "Fruit Punch", "Tiki Drink"],
    "🍺": ["Beer Mug", "Beer", "Beer Stein"],
    "🍻": ["Clinking Beer Mugs", "Beers", "Cheers"],
    "🥂": ["Clinking Glasses", "Celebration", "Champagne Glasses", "Cheers"],
    "🥃": ["Tumbler Glass", "Bourbon", "Liquor", "Rum", "Whiskey", "Whisky"],
    "🥤": ["Cup with Straw", "Milkshake", "Smoothie", "Soda Pop", "Soft Drink"],
    "🥢": ["Chopsticks"],
    "🍽️": ["Fork and Knife with Plate", "Dinner"],
    "🍴": ["Fork and Knife", "Cutlery", "Knife And Fork", "Silverware"],
    "🥄": ["Spoon"]
};
/*flags*/
emojis[6] = {
    "🏁": ["Chequered Flag", "Checkered Flag", "Grid Girl", "Racing Flag"],
    "🚩": ["Triangular Flag", "Flag on Pole", "Red Flag", "Triangular Flag on Post"],
    "🎌": ["Crossed Flags", "Two Flags"],
    "🏴": ["Black Flag", "Waving Black Flag"],
    "🏳️": ["White Flag", "Waving White Flag"],
    "🏳️‍🌈": ["Rainbow Flag", "Pride Flag"],
    "🏴‍☠️": ["Pirate Flag", "Jolly Roger"],
    "🇺🇳": ["UN", "Flag: United Nations", "United Nations Flag"],
    "🇪🇺": ["Flag: European Union", "EU Flag", "Flag of European Union"],
    "🇧🇸": ["Bahamian Flag", "Flag of Bahamas", "BS"],
    "🇨🇦": ["Canadian Flag", "Flag of Canada", "CA"],
    "🇨🇭": ["Red Cross", "Swiss Flag", "Flag of Switzerland", "CH"],
    "🇨🇳": ["Chinese Flag", "Flag of China", "CN"],
    "🇩🇪": ["Deutsch Flag", "German Flag", "Flag of Germany", "DE"],
    "🇩🇰": ["DK", "Danish Flag", "Flag of Denmark"],
    "🇪🇪": ["EE", "Estonian Flag", "Flag of Estonia"],
    "🇪🇬": ["EG", "Egyptian Flag", "Flag of Egypt"],
    "🇪🇸": ["ES", "Spanish Flag", "Flag of Spain"],
    "🇫🇮": ["FI", "Finnish Flag", "Flag of Finland"],
    "🇫🇷": ["FR", "French Flag", "Flag of France"],
    "🇬🇧": ["GB", "British Flag", "Flag of Great Britain", "United Kingdom", "Union Jack", "UK", "G.B.", "U.K."],
    "🇬🇱": ["GL", "Greenlandic Flag", "Flag of Greenland"],
    "🇬🇷": ["GR", "Greek Flag", "Flag of Greece"],
    "🇭🇺": ["HU", "Hungarian Flag", "Flag of Hungary"],
    "🇮🇪": ["IE", "Irish Flag", "Flag of Ireland"],
    "🇮🇱": ["IL", "Israeli Flag", "Flag of Israel"],
    "🇮🇩": ["ID", "Indonesian Flag", "Flag of Indonesia"],
    "🇮🇳": ["IN", "Indian Flag", "Flag of India"],
    "🇮🇶": ["IQ", "Iraqi Flag", "Flag of Iraq"],
    "🇮🇷": ["IR", "Iranian Flag", "Flag of Iran"],
    "🇮🇸": ["IS", "Icelandic Flag", "Flag of Iceland"],
    "🇮🇹": ["IT", "Italian Flag", "Flag of Italy"],
    "🇯🇵": ["JP", "Japanese Flag", "Flag of Japan"],
    "🇯🇲": ["JM", "Jamaican Flag", "Flag of Jamaica"],
    "🇰🇪": ["KE", "Kenyan Flag", "Flag of Kenya"],
    "🇰🇷": ["KR", "South Korean Flag", "Flag of South Korea"],
    "🇰🇵": ["KP", "North Korean Flag", "Flag of North Korea"],
    "🇱🇺": ["LU", "Luxembourger Flag", "Flag of Luxembourg"],
    "🇲🇹": ["MT", "Maltese Flag", "Flag of Malta"],
    "🇲🇽": ["MX", "Mexican Flag", "Flag of Mexico"],
    "🇳🇴": ["NO", "Norwegian Flag", "Flag of Norway"],
    "🇳🇱": ["NL", "Dutch Flag", "Flag of Netherlands"],
    "🇳🇿": ["NZ", "Kiwi Flag", "Flag of New Zealand"],
    "🇵🇱": ["PL", "Polish Flag", "Flag of Poland"],
    "🇵🇹": ["PT", "Portugese Flag", "Flag of Portugal"],
    "🇷🇺": ["RU", "Russian Flag", "Flag of Russia"],
    "🇸🇪": ["SE", "Swedish Flag", "Flag of Sweden"],
    "🇸🇮": ["SI", "Slovenian Flag", "Flag of Slovenia"],
    "🇹🇳": ["TN", "Tunisian Flag", "Flag of Tunisia"],
    "🇺🇦": ["UA", "Ukrainian Flag", "Flag of Ukraine"],
    "🇺🇸": ["US", "American Flag", "USA Flag", "Flag of United States", "U.S.A."],
    "🇻🇪": ["VE", "Venezuelan Flag", "Flag of Venezuela"],
    "🇻🇬": ["VG", "British Virgin Islander Flag", "Flag of British Virgin Islands"],
    "🇻🇮": ["VI", "US Virgin Islander Flag", "Flag of US Virgin Islands", "U.S."],
    "🇿🇦": ["ZA", "South African Flag", "Flag of South Africa"],
    "🇿🇼": ["ZW", "Zimbabwean Flag", "Zim Flag", "Flag of Zimbabwe"],
    "🇦🇪": ["AE", "Emirati Flag", "UAE Flag", "U.A.E.", "Flag of United Arab Emirates"],
    "🇦🇷": ["AR", "Argentinian Flag", "Flag of Argentina"],
    "🇦🇹": ["AT", "Austrian Flag", "Flag of Austria"],
    "🇦🇺": ["AU", "Aussie Flag", "Australian Flag", "Flag of Australia"],
    "🇧🇷": ["BR", "Brazilian Flag", "Flag For Brasil", "Flag of Brazil"]
};
/*sports*/
emojis[7] = {
    "🧗": [],
    "🏇": [],
    "⛷️": [],
    "🏂": [],
    "🏌️": [],
    "🏄": [],
    "🚣": [],
    "🏊": [],
    "⛹️": [],
    "🏋️": [],
    "🚴": [],
    "🚵": [],
    "🤸": [],
    "🤼": [],
    "🤽": [],
    "🤾": [],
    "🤹": [],
    "🧘": [],
    "🏆": [],
    "🏅": [],
    "🥇": [],
    "🥈": [],
    "🥉": [],
    "⚽": [],
    "⚾": [],
    "🥎": [],
    "🏀": [],
    "🏐": [],
    "🏈": [],
    "🏉": [],
    "🎾": [],
    "🥏": [],
    "🎳": [],
    "🏏": [],
    "🏑": [],
    "🏒": [],
    "🥍": [],
    "🏓": [],
    "🏸": [],
    "🥊": [],
    "🥋": [],
    "⛳": [],
    "⛸️": [],
    "🎣": [],
    "🎽": [],
    "🎿": [],
    "🛷": [],
    "🥌": [],
    "🎯": [],
    "🎱": [],
    "🎮": [],
    "♟️": [],
    "🏹": []
};
/*travel and places*/
emojis[8] = {
    "✈️": ["Airplane"]
};
/*technologies (smartphones, laptops, ect.) and office*/
emojis[9] = {
    "⌚": [],
    "⏰": [],
    "⏱️": [],
    "⏲️": [],
    "🕰️": [],
    "🕹️": [],
    "🎙️": [],
    "🎚️": [],
    "🎛️": [],
    "📻": [],
    "📱": [],
    "📲": [],
    "☎️": [],
    "📞": [],
    "📟": [],
    "📠": [],
    "🔋": [],
    "🔌": [],
    "💻": [],
    "🖥️": [],
    "🖨️": [],
    "⌨️": [],
    "🖱️": [],
    "🖲️": [],
    "💽": [],
    "💾": [],
    "💿": [],
    "📀": [],
    "🎥": [],
    "🎞️": [],
    "📽️": [],
    "📺": [],
    "📷": [],
    "📸": [],
    "📹": [],
    "📼": [],
    "💳": [],
    "📧": [],
    "📨": [],
    "📩": [],
    "📤": [],
    "📥": [],
    "📮": [],
    "📁": [],
    "📂": [],
    "🗂️": [],
    "📅": [],
    "📈": [],
    "📉": [],
    "📊": [],
    "📌": [],
    "📋": [],
    "📍": [],
    "📎": [],
    "📏": [],
    "📐": [],
    "✂️": [],
    "✏️": [],
    "✒️": [],
    "🖋️": [],
    "🖊️": [],
    "🖌️": [],
    "🖍️": [],
    "📝": [],
    "🗑️": [],
    "📡": [],
    "🔭": [],
    "🔬": []
};
/*clothes and accessories*/
emojis[10] = {
    "👣": [],
    "👓": [],
    "🕶️": [],
    "🥽": [],
    "🥼": [],
    "👔": [],
    "👕": [],
    "👖": [],
    "🧣": [],
    "🧤": [],
    "🧥": [],
    "🧦": [],
    "👗": [],
    "👘": [],
    "👙": [],
    "👚": [],
    "👛": [],
    "👜": [],
    "👝": [],
    "🎒": [],
    "👞": [],
    "👟": [],
    "🥾": [],
    "🥿": [],
    "👠": [],
    "👡": [],
    "👢": [],
    "👑": [],
    "👒": [],
    "🎩": [],
    "🎓": [],
    "🧢": [],
    "⛑️": [],
    "💼": []
};
/*hands and parts of body*/
emojis[11] = {
    "👋": [],
    "🤚": [],
    "✋": [],
    "🖖": [],
    "👌": [],
    "✌️": [],
    "🤞": [],
    "🤟": [],
    "🤘": [],
    "🤙": [],
    "🤏": [],
    "👈": [],
    "👉": [],
    "👆": [],
    "👇": [],
    "☝️": [],
    "🖕": [],
    "👍": [],
    "👎": [],
    "✊": [],
    "👊": [],
    "🤛": [],
    "🤜": [],
    "👏": [],
    "🙌": [],
    "👐": [],
    "🤲": [],
    "🤝": [],
    "🙏": [],
    "✍️": [],
    "💪": [],
    "🦵": [],
    "🦶": [],
    "👂": [],
    "👃": [],
    "🧠": [],
    "🦷": [],
    "👀": [],
    "👁️": [],
    "👅": [],
    "👄": []
};
/*other*/
emojis[12] = {
    "💩": [],
    "💋": [],
    "💅": [],
    "🤳": [],
    "🦴": [],
    "🧳": [],
    "🌂": [],
    "☂️": [],
    "🧵": [],
    "🧶": [],
    "💄": [],
    "💍": [],
    "💥": [],
    "💫": [],
    "💦": [],
    "💨": [],
    "🐾": [],
    "🕸️": [],
    "🦠": [],
    "💐": [],
    "🌍": [],
    "🌎": [],
    "🌏": [],
    "🌐": [],
    "🌑": [],
    "🌓": [],
    "🌕": [],
    "🌗": [],
    "🌙": [],
    "🌛": [],
    "🌜": [],
    "☀️": [],
    "⭐": [],
    "☁️": [],
    "⛅": [],
    "⛈️": [],
    "🌤️": [],
    "🌥️": [],
    "🌦️": [],
    "🌧️": [],
    "🌨️": [],
    "🌩️": [],
    "🌪️": [],
    "🌫️": [],
    "🌈": [],
    "❄️": [],
    "☃️": [],
    "⛄": [],
    "☄️": [],
    "🔥": [],
    "💧": [],
    "🌊": [],
    "🎄": [],
    "🌻": [],
    "🌼": [],
    "🌷": [],
    "🌹": [],
    "🌹": [],
    "🌳": [],
    "🌴": [],
    "☘️": [],
    "🔑": [],
    "🗝️": [],
    "🔨": [],
    "⛏️": [],
    "🔒": [],
    "🔓": [],
    "🔏": [],
    "🔐": [],
    "🗡️": [],
    "⚔️": [],
    "🔫": [],
    "🧰": [],
    "🧲": [],
    "⛓️": [],
    "💉": [],
    "🧬": [],
    "🧪": [],
    "🛏️": [],
    "🚪": [],
    "🚽": [],
    "🚿": [],
    "🛁": [],
    "🧴": [],
    "🧷": [],
    "🧺": [],
    "🧻": [],
    "🧼": [],
    "🧽": [],
    "🧯": [],
    "🚬": [],
    "⚰️": [],
    "⚱️": [],
    "🗿": [],
    "🛡️": [],
    "⚙️": [],
    "⚖️": [],
    "🔗": [],
    "💀": [],
    "☠️": [],
    "🦻": [],
    "🦸": [],
    "🦸‍♀️": [],
    "🦹": [],
    "🦹‍♀️": [],
    "🧙": [],
    "🧙‍♀️": [],
    "🧚": [],
    "🧚‍♀️": [],
    "🧛": [],
    "🧛‍♀️": [],
    "🧜": [],
    "🧜‍♀️": [],
    "🧝": [],
    "🧝‍♀️": [],
    "🧞‍♂️": [],
    "🧞": [],
    "🕵️": [],
    "💂": [],
    "💂‍♀️": [],
    "👮": [],
    "👮‍♀️": [],
    "👨‍🚒": [],
    "👩‍🚒": [],
    "👨‍‍✈️": [],
    "👩‍✈️": [],
    "👨‍‍💻": [],
    "👩‍💻": [],
    "👨‍‍🎤": [],
    "👩‍🎤": [],
    "👨‍‍🎨": [],
    "👩‍🎨": [],
    "👷‍♂️": [],
    "👷‍♀️": [],
    "💑": [],
    "👨‍❤️‍👨": [],
    "👩‍❤️‍👩": []
};